In [1]:
# Import libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import glob
import os

**Step 1: Merging all country files in the target folder: AF Market share of total registrations (M1)**

In [2]:
# Path to all country-level Excel files
target_files_marketShare = glob.glob(r"C:\Users\Disha\TU Braunschweig\Thesis\Data_2025\Target_2025\AF Market share of total registrations (M1)\*.csv")

# To make sure the files are present
print("Files found:", len(target_files_marketShare))
print(target_files_marketShare[:5])

Files found: 27
['C:\\Users\\Disha\\TU Braunschweig\\Thesis\\Data_2025\\Target_2025\\AF Market share of total registrations (M1)\\Austria.csv', 'C:\\Users\\Disha\\TU Braunschweig\\Thesis\\Data_2025\\Target_2025\\AF Market share of total registrations (M1)\\Belgium.csv', 'C:\\Users\\Disha\\TU Braunschweig\\Thesis\\Data_2025\\Target_2025\\AF Market share of total registrations (M1)\\Bulgaria.csv', 'C:\\Users\\Disha\\TU Braunschweig\\Thesis\\Data_2025\\Target_2025\\AF Market share of total registrations (M1)\\Croatia.csv', 'C:\\Users\\Disha\\TU Braunschweig\\Thesis\\Data_2025\\Target_2025\\AF Market share of total registrations (M1)\\Cyprus.csv']

In [3]:
target_list = []

for file in target_files_marketShare:
    
    # Extract country name from filename 
    country = os.path.basename(file).split(".")[0]
    
    # Read the CSV/Excel file
    df = pd.read_csv(file)
    # If Excel files, use: pd.read_excel(file)
    
    # Rename the first column to 'Year' (previously 'Category')
    df = df.rename(columns={df.columns[0]: "Year"})
    
    # Keep only required columns
    df = df[["Year", "BEV"]].copy()
    
    # Clean up 'Country' values (remove "(Target)" if it exists)
    df["Country"] = country.replace("(Target)", "").strip()
    
    # Ensure Year is numeric
    df = df[pd.to_numeric(df["Year"], errors="coerce").notnull()]
    df["Year"] = df["Year"].astype(int)
    
    # Rearranging the columns
    df = df[["Country", "Year", "BEV"]]
    
    # Append to the list
    target_list.append(df)

# Combine all countries into one DataFrame
targets_marketShare = pd.concat(target_list, ignore_index=True)

print("Target data combined. Shape:", targets_marketShare.shape)
display(targets_marketShare.head())

Target data combined. Shape: (486, 3)

   Country  Year   BEV
0  Austria  2008   NaN
1  Austria  2009  0.01
2  Austria  2010  0.03
3  Austria  2011  0.18
4  Austria  2012  0.13

In [4]:
targets_marketShare['Country'].unique()

array(['Austria', 'Belgium', 'Bulgaria', 'Croatia', 'Cyprus',
       'Czech Republic', 'Denmark', 'Estonia', 'Finland', 'France',
       'Germany', 'Greece', 'Hungary', 'Ireland', 'Italy', 'Latvia',
       'Lithuania', 'Luxembourg', 'Malta', 'Netherlands', 'Poland',
       'Portugal', 'Romania', 'Slovakia', 'Slovenia', 'Spain', 'Sweden'],
      dtype=object)

**Step 3: Gross Domestic Product (GDP)**

In [5]:
# Read the GDP data
gdp_wide = pd.read_csv(r"C:\Users\Disha\TU Braunschweig\Thesis\Data_2025\Parameters_2025\GDP_EU27_Anually.csv")
gdp_wide.head()

,Country,2011,2012,2013,2014,2015,2016,2017,2018,2019,2020,2021,2022,2023,2024,2025
0,Austria,"308,167.00","316,589.40","321,191.70","330,113.50","342,083.50","355,665.60","367,294.90","383,234.30","395,706.80","380,317.90","406,231.50","449,382.20","477,837.30","494,087.60",NaN
1,Belgium,"378,745.40","387,934.90","394,616.30","404,958.30","415,538.00","428,467.10","443,407.20","459,491.80","479,444.90","463,750.90","506,047.20","561,309.10","602,376.30","620,271.80",NaN
2,Bulgaria,"81,126.30","82,642.80","82,253.40","84,147.70","89,571.40","95,349.40","102,683.00","109,525.90","119,685.90","120,979.00","139,536.60","168,354.30","184,875.00","204,906.90",NaN
3,Croatia,"45,178.90","44,791.50","45,061.50","44,867.90","45,965.70","47,565.90","49,732.50","52,216.70","54,905.50","50,744.00","58,343.10","67,613.00","79,186.30","85,905.20",NaN
4,Cyprus,"19,858.10","19,495.40","18,040.30","17,482.80","17,944.20","19,013.80","20,312.40","21,807.80","23,400.90","22,373.60","25,679.90","29,645.40","32,439.20","34,770.20",NaN

In [6]:
# Transpose the datset 
gdp = gdp_wide.melt(id_vars="Country", var_name="Year", value_name="GDP")

# Sort by Country and then Year
gdp = gdp.sort_values(by=["Country", "Year"]).reset_index(drop=True)

# Display
gdp.head()

   Country  Year         GDP
0  Austria  2011  308,167.00
1  Austria  2012  316,589.40
2  Austria  2013  321,191.70
3  Austria  2014  330,113.50
4  Austria  2015  342,083.50

In [7]:
gdp['Country'].unique()

array(['Austria', 'Belgium', 'Bulgaria', 'Croatia', 'Cyprus', 'Czechia',
       'Denmark', 'Estonia', 'Finland', 'France', 'Germany', 'Greece',
       'Hungary', 'Ireland', 'Italy', 'Latvia', 'Lithuania', 'Luxembourg',
       'Malta', 'Netherlands', 'Poland', 'Portugal', 'Romania',
       'Slovakia', 'Slovenia', 'Spain', 'Sweden'], dtype=object)

In [8]:
# Rename the name from 'Czechia' to 'Czech Republic'
gdp.loc[gdp['Country'] == 'Czechia', 'Country'] = 'Czech Republic'
gdp['Country'].unique()

array(['Austria', 'Belgium', 'Bulgaria', 'Croatia', 'Cyprus',
       'Czech Republic', 'Denmark', 'Estonia', 'Finland', 'France',
       'Germany', 'Greece', 'Hungary', 'Ireland', 'Italy', 'Latvia',
       'Lithuania', 'Luxembourg', 'Malta', 'Netherlands', 'Poland',
       'Portugal', 'Romania', 'Slovakia', 'Slovenia', 'Spain', 'Sweden'],
      dtype=object)

**Step 4: Consumer Price Index (CPI)**

In [9]:
# Read the CPI data
cpi_wide = pd.read_csv(r"C:\Users\Disha\TU Braunschweig\Thesis\Data_2025\Parameters_2025\ConsumerPriceIndex_EU27_Anually.csv")
cpi_wide.head()

,DATASET,SERIES_CODE,OBS_MEASURE,COUNTRY,INDEX_TYPE,COICOP_1999,TYPE_OF_TRANSFORMATION,FREQUENCY,SCALE,2020,2021,2022,2023,2024,2025
0,IMF.STA:CPI(5.0.0),LUX.CPI._T.YOY_PCH_PA_PT.A,OBS_VALUE,Luxembourg,Consumer price index (CPI),All Items,"Period average, Year-over-year (YOY) percent c...",Annual,Units,0.819957,2.526920,6.336008,3.741404,2.051133,NaN
1,IMF.STA:CPI(5.0.0),MLT.CPI._T.YOY_PCH_PA_PT.A,OBS_VALUE,Malta,Consumer price index (CPI),All Items,"Period average, Year-over-year (YOY) percent c...",Annual,Units,0.638545,1.497892,6.153756,5.093968,1.650795,NaN
2,IMF.STA:CPI(5.0.0),CYP.CPI._T.YOY_PCH_PA_PT.A,OBS_VALUE,Cyprus,Consumer price index (CPI),All Items,"Period average, Year-over-year (YOY) percent c...",Annual,Units,-0.638423,2.446089,8.395483,3.541342,1.800230,NaN
3,IMF.STA:CPI(5.0.0),ROU.CPI._T.YOY_PCH_PA_PT.A,OBS_VALUE,Romania,Consumer price index (CPI),All Items,"Period average, Year-over-year (YOY) percent c...",Annual,Units,2.631073,5.052329,13.795489,10.397187,5.721406,NaN
4,IMF.STA:CPI(5.0.0),BEL.CPI._T.YOY_PCH_PA_PT.A,OBS_VALUE,Belgium,Consumer price index (CPI),All Items,"Period average, Year-over-year (YOY) percent c...",Annual,Units,0.740792,2.440249,9.597512,4.049011,3.143491,2.467055

In [10]:
# Drop unwanted columns
cpi_wide = cpi_wide.drop(columns=['DATASET','SERIES_CODE', 'OBS_MEASURE', 'INDEX_TYPE', 'COICOP_1999',
                        'TYPE_OF_TRANSFORMATION', 'FREQUENCY', 'SCALE'])
cpi_wide.head()

      COUNTRY      2020      2021       2022       2023      2024      2025
0  Luxembourg  0.819957  2.526920   6.336008   3.741404  2.051133       NaN
1       Malta  0.638545  1.497892   6.153756   5.093968  1.650795       NaN
2      Cyprus -0.638423  2.446089   8.395483   3.541342  1.800230       NaN
3     Romania  2.631073  5.052329  13.795489  10.397187  5.721406       NaN
4     Belgium  0.740792  2.440249   9.597512   4.049011  3.143491  2.467055

In [11]:
# Sort by Country alphabetically
cpi_wide = cpi_wide.sort_values(by="COUNTRY").reset_index(drop=True)

# Display result
cpi_wide.head()

,COUNTRY,2020,2021,2022,2023,2024,2025
0,Austria,1.381911,2.766667,8.546870,7.814134,2.937916,3.527194
1,Belgium,0.740792,2.440249,9.597512,4.049011,3.143491,2.467055
2,Bulgaria,1.672441,3.297744,15.325259,9.442841,2.446519,4.580844
3,"Croatia, Republic of",0.154811,2.554507,10.780581,7.941282,2.972005,3.691535
4,Cyprus,-0.638423,2.446089,8.395483,3.541342,1.800230,NaN

In [12]:
# Rename column
cpi_wide = cpi_wide.rename(columns={"COUNTRY": "Country"})

# Remove "Republic of " prefix from country names
cpi_wide["Country"] = cpi_wide["Country"].str.split(",").str[0].str.strip()

# Display
cpi_wide.head()

    Country      2020      2021       2022      2023      2024      2025
0   Austria  1.381911  2.766667   8.546870  7.814134  2.937916  3.527194
1   Belgium  0.740792  2.440249   9.597512  4.049011  3.143491  2.467055
2  Bulgaria  1.672441  3.297744  15.325259  9.442841  2.446519  4.580844
3   Croatia  0.154811  2.554507  10.780581  7.941282  2.972005  3.691535
4    Cyprus -0.638423  2.446089   8.395483  3.541342  1.800230       NaN

In [13]:
# Transpose the datset 
cpi = cpi_wide.melt(id_vars="Country", var_name="Year", value_name="CPI")

# Sort by Country and then Year
cpi = cpi.sort_values(by=["Country", "Year"]).reset_index(drop=True)

# Display
cpi.head()

   Country  Year       CPI
0  Austria  2020  1.381911
1  Austria  2021  2.766667
2  Austria  2022  8.546870
3  Austria  2023  7.814134
4  Austria  2024  2.937916

In [14]:
cpi['Country'].unique()

array(['Austria', 'Belgium', 'Bulgaria', 'Croatia', 'Cyprus',
       'Czech Republic', 'Denmark', 'Estonia', 'Finland', 'France',
       'Germany', 'Greece', 'Hungary', 'Ireland', 'Italy', 'Latvia',
       'Lithuania', 'Luxembourg', 'Malta', 'Netherlands', 'Poland',
       'Portugal', 'Romania', 'Slovak Republic', 'Slovenia', 'Spain',
       'Sweden'], dtype=object)

In [15]:
# Rename the name from 'Czechia' to 'Czech Republic'
cpi.loc[cpi['Country'] == 'Slovak Republic', 'Country'] = 'Slovakia'
cpi['Country'].unique()

array(['Austria', 'Belgium', 'Bulgaria', 'Croatia', 'Cyprus',
       'Czech Republic', 'Denmark', 'Estonia', 'Finland', 'France',
       'Germany', 'Greece', 'Hungary', 'Ireland', 'Italy', 'Latvia',
       'Lithuania', 'Luxembourg', 'Malta', 'Netherlands', 'Poland',
       'Portugal', 'Romania', 'Slovakia', 'Slovenia', 'Spain', 'Sweden'],
      dtype=object)

**Step 5: Employment Growth**

In [16]:
# Read the Employment Growth data
eg_wide = pd.read_csv(r"C:\Users\Disha\TU Braunschweig\Thesis\Data\Parameters\EmploymentGrowth_EU27_Anually.csv")
eg_wide.head()

,Country,2005,2006,2007,2008,2009,2010,2011,2012,2013,...,2015,2016,2017,2018,2019,2020,2021,2022,2023,2024
0,Belgium,1.4,1.1,1.7,1.8,-0.1,0.7,1.2,0.2,-0.2,...,0.8,1.3,1.5,1.5,1.6,-0.1,1.7,1.9,0.8,0.3
1,Bulgaria,2.7,3.3,3.2,2.4,-1.7,-3.9,-2.2,-2.5,-0.4,...,0.4,0.5,1.8,-0.1,-1.5,-1.8,0.1,1.1,1.1,1.1
2,Czechia,1.9,1.3,2.1,2.2,-1.8,-1.0,-0.5,0.5,0.4,...,1.4,1.0,1.3,1.2,-0.1,-2.3,1.0,1.0,1.6,0.6
3,Denmark,1.4,2.3,2.3,1.3,-3.1,-2.3,-0.1,-0.7,0.0,...,1.5,1.6,1.5,1.5,1.4,-1.1,2.3,4.0,1.1,0.7
4,Germany,-0.1,0.7,1.7,1.4,0.1,0.5,1.1,1.2,0.7,...,0.9,1.3,1.4,1.3,0.9,-0.7,0.2,1.3,0.7,0.1

In [17]:
# Transpose the datset 
eg = eg_wide.melt(id_vars="Country", var_name="Year", value_name="EG")

# Sort by Country and then Year
eg = eg.sort_values(by=["Country", "Year"]).reset_index(drop=True)

# Display
eg.head()

   Country  Year EG
0  Albania  2005  :
1  Albania  2006  :
2  Albania  2007  :
3  Albania  2008  :
4  Albania  2009  :

In [18]:
eg['Country'].unique()

array(['Albania', 'Austria', 'Belgium', 'Bulgaria', 'Croatia', 'Cyprus',
       'Czechia', 'Denmark', 'Estonia', 'Finland', 'France', 'Germany',
       'Greece', 'Hungary', 'Iceland', 'Ireland', 'Italy', 'Kosovo*',
       'Latvia', 'Liechtenstein', 'Lithuania', 'Luxembourg', 'Malta',
       'Montenegro', 'Netherlands', 'North Macedonia', 'Norway', 'Poland',
       'Portugal', 'Romania', 'Serbia', 'Slovakia', 'Slovenia', 'Spain',
       'Sweden', 'Switzerland', 'Türkiye', 'United Kingdom'], dtype=object)

In [19]:
# Keep only those countries those are part of EU27
countries_to_remove = [
    'Albania', 'Iceland', 'Norway', 'Kosovo*', 'Liechtenstein',
    'Montenegro', 'North Macedonia','Switzerland', 'Türkiye', 'United Kingdom', 'Serbia'
]

eg = eg[~eg['Country'].isin(countries_to_remove)]

eg['Country'].unique()

array(['Austria', 'Belgium', 'Bulgaria', 'Croatia', 'Cyprus', 'Czechia',
       'Denmark', 'Estonia', 'Finland', 'France', 'Germany', 'Greece',
       'Hungary', 'Ireland', 'Italy', 'Latvia', 'Lithuania', 'Luxembourg',
       'Malta', 'Netherlands', 'Poland', 'Portugal', 'Romania',
       'Slovakia', 'Slovenia', 'Spain', 'Sweden'], dtype=object)

In [20]:
# Rename the name from 'Czechia' to 'Czech Republic'
eg.loc[eg['Country'] == 'Czechia', 'Country'] = 'Czech Republic'
eg['Country'].unique()

array(['Austria', 'Belgium', 'Bulgaria', 'Croatia', 'Cyprus',
       'Czech Republic', 'Denmark', 'Estonia', 'Finland', 'France',
       'Germany', 'Greece', 'Hungary', 'Ireland', 'Italy', 'Latvia',
       'Lithuania', 'Luxembourg', 'Malta', 'Netherlands', 'Poland',
       'Portugal', 'Romania', 'Slovakia', 'Slovenia', 'Spain', 'Sweden'],
      dtype=object)

**Step 6: Recharging Points**

In [21]:
# Path to all country-level Excel files
recharge_files_2019 = glob.glob(r"C:\Users\Disha\TU Braunschweig\Thesis\Data_2025\Parameters_2025\Recharging points (2012-2019)\*.csv")

# To make sure the files are present
print("Files found:", len(recharge_files_2019))
print(recharge_files_2019[:5])

Files found: 33
['C:\\Users\\Disha\\TU Braunschweig\\Thesis\\Data_2025\\Parameters_2025\\Recharging points (2012-2019)\\Austria.csv', 'C:\\Users\\Disha\\TU Braunschweig\\Thesis\\Data_2025\\Parameters_2025\\Recharging points (2012-2019)\\Belgium.csv', 'C:\\Users\\Disha\\TU Braunschweig\\Thesis\\Data_2025\\Parameters_2025\\Recharging points (2012-2019)\\Bulgaria.csv', 'C:\\Users\\Disha\\TU Braunschweig\\Thesis\\Data_2025\\Parameters_2025\\Recharging points (2012-2019)\\Croatia.csv', 'C:\\Users\\Disha\\TU Braunschweig\\Thesis\\Data_2025\\Parameters_2025\\Recharging points (2012-2019)\\Cyprus.csv']

In [22]:
recharging_2019_list = []

for file in recharge_files_2019:
    
    # Extract country name from filename 
    country = os.path.basename(file).split(".")[0]
    
    # Read the CSV file
    df_2019 = pd.read_csv(file)
    
    # Rename the first column to 'Year'
    df_2019 = df_2019.rename(columns={df_2019.columns[0]: "Year"})
    
    # Rename the second column (which is the country name) to 'Recharging Points'
    df_2019 = df_2019.rename(columns={df_2019.columns[1]: "Recharging Points"})
    
    # Clean up Year column and keep only valid numeric years
    df_2019 = df_2019[pd.to_numeric(df_2019["Year"], errors="coerce").notnull()]
    df_2019["Year"] = df_2019["Year"].astype(int)
    
    # Add a Country column
    df_2019["Country"] = country.replace("(Target)", "").strip()
    
    # Reorder columns
    df_2019 = df_2019[["Country", "Year", "Recharging Points"]]
    
    # Append to list
    recharging_2019_list.append(df_2019)

# Combine all countries into one DataFrame
recharge_files_2019 = pd.concat(recharging_2019_list, ignore_index=True)

print("Target data combined. Shape:", recharge_files_2019.shape)
display(recharge_files_2019.head())

Target data combined. Shape: (264, 3)

   Country  Year  Recharging Points
0  Austria  2012             1063.0
1  Austria  2013             1173.0
2  Austria  2014             1393.0
3  Austria  2015             1625.0
4  Austria  2016             1998.0

In [23]:
# Path to all country-level Excel files
recharge_files_2025 = glob.glob(r"C:\Users\Disha\TU Braunschweig\Thesis\Data\Parameters\Recharging points (2020-2025)\*.csv")

# To make sure the files are present
print("Files found:", len(recharge_files_2025))
print(recharge_files_2025[:5])

Files found: 33
['C:\\Users\\Disha\\TU Braunschweig\\Thesis\\Data\\Parameters\\Recharging points (2020-2025)\\Austria.csv', 'C:\\Users\\Disha\\TU Braunschweig\\Thesis\\Data\\Parameters\\Recharging points (2020-2025)\\Belgium.csv', 'C:\\Users\\Disha\\TU Braunschweig\\Thesis\\Data\\Parameters\\Recharging points (2020-2025)\\Bulgaria.csv', 'C:\\Users\\Disha\\TU Braunschweig\\Thesis\\Data\\Parameters\\Recharging points (2020-2025)\\Croatia.csv', 'C:\\Users\\Disha\\TU Braunschweig\\Thesis\\Data\\Parameters\\Recharging points (2020-2025)\\Cyprus.csv']

In [24]:
recharging_2025_list = []

for file in recharge_files_2025:
    
    # Extract country name from filename 
    country = os.path.basename(file).split(".")[0]
    
    # Read the CSV file
    df_2025 = pd.read_csv(file)
    
    # Rename first column to 'Period'
    df_2025 = df_2025.rename(columns={df_2025.columns[0]: "Period"})
    
    # Extract numeric year from 'Period' (e.g. '2020 Q1' -> 2020)
    df_2025["Year"] = df_2025["Period"].str.extract(r"(\d{4})").astype(int)
    
    # Group by year to sum all quarters (sum AC and DC, individually)
    df_2025_yearly = df_2025.groupby("Year", as_index=False)[["AC", "DC"]].sum()
    
    # Add total recharging points (AC + DC)
    df_2025_yearly["Recharging Points"] = df_2025_yearly["AC"] + df_2025_yearly["DC"]
    
    # Add country name
    df_2025_yearly["Country"] = country.replace("(Target)", "").strip()
    
    # Reorder columns
    df_2025_yearly = df_2025_yearly[["Country", "Year", "Recharging Points"]]
    
    # Append to list
    recharging_2025_list.append(df_2025_yearly)

# Combine all countries into one DataFrame
recharge_files_2025 = pd.concat(recharging_2025_list, ignore_index=True)

print("Target data combined. Shape:", recharge_files_2025.shape)
display(recharge_files_2025.head())

Target data combined. Shape: (198, 3)

   Country  Year  Recharging Points
0  Austria  2020            26797.0
1  Austria  2021            39904.0
2  Austria  2022            61393.0
3  Austria  2023            76773.0
4  Austria  2024           102562.0

In [25]:
# Combine both dataframe (recharge_files_2019 and recharge_files_2025)

# Make sure both dataframes exist
print("Old data:", recharge_files_2019.shape)
print("New data:", recharge_files_2025.shape)

# Ensure same column names and order
recharge_files_2019 = recharge_files_2019[["Country", "Year", "Recharging Points"]]
recharge_files_2025 = recharge_files_2025[["Country", "Year", "Recharging Points"]]

# Concatenate vertically
recharging_points = pd.concat(
    [recharge_files_2019, recharge_files_2025], 
    ignore_index=True
)

# Keep only rows where Year <= 2024 
recharging_points = recharging_points[recharging_points["Year"] <= 2024]

# Sort by Country and Year
recharging_points = recharging_points.sort_values(
    by=["Country", "Year"]
).reset_index(drop=True)

# Check the result
print("Combined dataset shape:", recharging_points.shape)
display(recharging_points.head(15))

Old data: (264, 3)
New data: (198, 3)
Combined dataset shape: (429, 3)

    Country  Year  Recharging Points
0   Austria  2012             1063.0
1   Austria  2013             1173.0
2   Austria  2014             1393.0
3   Austria  2015             1625.0
4   Austria  2016             1998.0
5   Austria  2017             3842.0
6   Austria  2018             4079.0
7   Austria  2019             7694.0
8   Austria  2020            26797.0
9   Austria  2021            39904.0
10  Austria  2022            61393.0
11  Austria  2023            76773.0
12  Austria  2024           102562.0
13  Belgium  2012                NaN
14  Belgium  2013              378.0

In [26]:
recharging_points['Country'].unique()

array(['Austria', 'Belgium', 'Bulgaria', 'Croatia', 'Cyprus',
       'Czech Republic', 'Denmark', 'Estonia', 'Finland', 'France',
       'Germany', 'Greece', 'Hungary', 'Iceland', 'Ireland', 'Italy',
       'Latvia', 'Liechtenstein', 'Lithuania', 'Luxembourg', 'Malta',
       'Netherlands', 'Norway', 'Poland', 'Portugal', 'Romania',
       'Slovakia', 'Slovenia', 'Spain', 'Sweden', 'Switzerland', 'Turkey',
       'United Kingdom'], dtype=object)

In [27]:
# Keep only those countries those are part of EU27
countries_to_remove = [
    'Iceland', 'Norway', 'Liechtenstein',
    'Switzerland', 'Turkey', 'United Kingdom'
]

recharging_points = recharging_points[~recharging_points['Country'].isin(countries_to_remove)]

recharging_points['Country'].unique()

array(['Austria', 'Belgium', 'Bulgaria', 'Croatia', 'Cyprus',
       'Czech Republic', 'Denmark', 'Estonia', 'Finland', 'France',
       'Germany', 'Greece', 'Hungary', 'Ireland', 'Italy', 'Latvia',
       'Lithuania', 'Luxembourg', 'Malta', 'Netherlands', 'Poland',
       'Portugal', 'Romania', 'Slovakia', 'Slovenia', 'Spain', 'Sweden'],
      dtype=object)

**Step 7: Merge these datasets with the target**

In [28]:
# Ensure 'Year' is numeric in all datasets
targets_marketShare["Year"] = targets_marketShare["Year"].astype(int)
gdp["Year"] = gdp["Year"].astype(int)
cpi["Year"] = cpi["Year"].astype(int)
eg["Year"] = eg["Year"].astype(int)
recharging_points["Year"] = recharging_points["Year"].astype(int)

# Ensure 'Country' is string in all datasets
targets_marketShare["Country"] = targets_marketShare["Country"].astype(str)
gdp["Country"] = gdp["Country"].astype(str)
cpi["Country"] = cpi["Country"].astype(str)
eg["Country"] = eg["Country"].astype(str)
recharging_points["Country"] = recharging_points["Country"].astype(str)

In [29]:
# Filter target dataset to years 2011-2024
targets_filtered_marketShare = targets_marketShare[(targets_marketShare["Year"] >= 2020) & (targets_marketShare["Year"] <= 2025)]

# Merge with GDP
merged_w_gdp = pd.merge(targets_filtered_marketShare, gdp, on=["Country", "Year"], how="left")

# Merge with CPI
merged_w_cpi = pd.merge(merged_w_gdp, cpi, on=["Country", "Year"], how="left")

# Merge with Employment Growth
merged_eg = pd.merge(merged_w_cpi, eg, on=["Country", "Year"], how="left")

# Merge with Recharging Points
merged_df = pd.merge(merged_eg, recharging_points, on=["Country", "Year"], how="left")

# Result
print("Shape of merged dataset:", merged_df.shape)
merged_df.head()

Shape of merged dataset: (162, 7)

   Country  Year    BEV         GDP       CPI    EG  Recharging Points
0  Austria  2020   6.41  380,317.90  1.381911  -1.6            26797.0
1  Austria  2021  13.92  406,231.50  2.766667   2.0            39904.0
2  Austria  2022  15.70  449,382.20  8.546870   2.7            61393.0
3  Austria  2023  19.91  477,837.30  7.814134   0.8            76773.0
4  Austria  2024  17.58  494,087.60  2.937916   0.1           102562.0

In [30]:
# Rename BEV columns
merged_df.rename(columns={
    'BEV': 'BEV Percentage (Total Number Of Registrations)'
}, inplace=True)

merged_df.head()

,Country,Year,BEV Percentage (Total Number Of Registrations),GDP,CPI,EG,Recharging Points
0,Austria,2020,6.41,"380,317.90",1.381911,-1.6,26797.0
1,Austria,2021,13.92,"406,231.50",2.766667,2.0,39904.0
2,Austria,2022,15.70,"449,382.20",8.546870,2.7,61393.0
3,Austria,2023,19.91,"477,837.30",7.814134,0.8,76773.0
4,Austria,2024,17.58,"494,087.60",2.937916,0.1,102562.0

**Step 8: Merge the EU average dataset with the country-wise merged dataset**

In [31]:
# Import the datasets
RechargeSpeed = pd.read_csv(r"C:\Users\Disha\TU Braunschweig\Thesis\Data_2025\Parameters_2025\AC and DC Average Recharging Speed of Available BEV Models.csv")
AvailableBEV = pd.read_csv(r"C:\Users\Disha\TU Braunschweig\Thesis\Data_2025\Parameters_2025\Available Battery Electric Vehicle models in Europ per year.csv")
AverageBatteryCapacity = pd.read_csv(r"C:\Users\Disha\TU Braunschweig\Thesis\Data_2025\Parameters_2025\Average Battery Capacity of Available BEV models per year.csv")
AverageRange = pd.read_csv(r"C:\Users\Disha\TU Braunschweig\Thesis\Data_2025\Parameters_2025\Average Range of BEV models per year.csv")
AverageRetailPrice = pd.read_csv(r"C:\Users\Disha\TU Braunschweig\Thesis\Data_2025\Parameters_2025\Average Retail Price of BEV models per year.csv")

In [32]:
RechargeSpeed.head()

   Category  AC Recharging Speed (km/h)  DC Recharging Speed (km/h)
0      2011                       17.50                      175.00
1      2013                       48.20                      270.00
2      2014                       22.60                      240.00
3      2015                       47.70                      381.25
4      2016                       44.85                      371.50

In [33]:
AvailableBEV.head()

   Category  Available
0      2011          4
1      2012          4
2      2013          8
3      2014         13
4      2015         21

In [34]:
AverageBatteryCapacity.head()

   Category  Battery Capacity
0      2011            16.375
1      2013            32.900
2      2014            33.260
3      2015            56.410
4      2016            62.485

In [35]:
AverageRange.head()

   Category  Real Range
0      2011       95.00
1      2012       95.00
2      2013      142.22
3      2014      155.77
4      2015      215.22

In [36]:
AverageRetailPrice.head()

   Category  Purchase price (EUR)
0      2013              30469.93
1      2014              35555.64
2      2015              42052.00
3      2016              39789.11
4      2017              44717.86

In [37]:
# Ensure all datasets have column named 'Year' as int
for df in [RechargeSpeed, AvailableBEV, AverageBatteryCapacity, AverageRange, AverageRetailPrice]:
    
    # Rename year column if needed
    if "Category" in df.columns:
        df.rename(columns={"Category": "Year"}, inplace=True)
    df["Year"] = df["Year"].astype(int)

In [38]:
# Merge with your country-level merged_df on 'Year' only
merged_df = merged_df.merge(RechargeSpeed, on="Year", how="left") \
                     .merge(AvailableBEV, on="Year", how="left") \
                     .merge(AverageBatteryCapacity, on="Year", how="left") \
                     .merge(AverageRange, on="Year", how="left") \
                     .merge(AverageRetailPrice, on="Year", how="left")

In [39]:
# Check result
print("Shape of final merged dataset:", merged_df.shape)
merged_df.head(20)

Shape of final merged dataset: (162, 13)

,Country,Year,BEV Percentage (Total Number Of Registrations),GDP,CPI,EG,Recharging Points,AC Recharging Speed (km/h),DC Recharging Speed (km/h),Available,Battery Capacity,Real Range,Purchase price (EUR)
0,Austria,2020,6.41,"380,317.90",1.381911,-1.6,26797.0,39.325301,403.164557,97.0,57.761446,286.20,38311.38
1,Austria,2021,13.92,"406,231.50",2.766667,2.0,39904.0,40.904348,493.391304,168.0,64.046957,308.73,40745.01
2,Austria,2022,15.70,"449,382.20",8.546870,2.7,61393.0,49.314815,594.259259,253.0,73.787037,345.44,43874.27
3,Austria,2023,19.91,"477,837.30",7.814134,0.8,76773.0,70.307692,649.230769,371.0,79.230769,NaN,45999.05
4,Austria,2024,17.58,"494,087.60",2.937916,0.1,102562.0,NaN,NaN,NaN,NaN,NaN,NaN
5,Austria,2025,21.34,NaN,3.527194,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,Belgium,2020,3.48,"463,750.90",0.740792,-0.1,28147.0,39.325301,403.164557,97.0,57.761446,286.20,38311.38
7,Belgium,2021,5.74,"506,047.20",2.440249,1.7,43781.0,40.904348,493.391304,168.0,64.046957,308.73,40745.01
8,Belgium,2022,10.32,"561,309.10",9.597512,1.9,72304.0,49.314815,594.259259,253.0,73.787037,345.44,43874.27
9,Belgium,2023,19.59,"602,376.30",4.049011,0.8,147542.0,70.307692,649.230769,371.0,79.230769,NaN,45999.05
10,Belgium,2024,28.38,"620,271.80",3.143491,0.3,263074.0,NaN,NaN,NaN,NaN,NaN,NaN
11,Belgium,2025,34.40,NaN,2.467055,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12,Bulgaria,2020,1.24,"120,979.00",1.672441,-1.8,609.0,39.325301,403.164557,97.0,57.761446,286.20,38311.38
13,Bulgaria,2021,2.24,"139,536.60",3.297744,0.1,1634.0,40.904348,493.391304,168.0,64.046957,308.73,40745.01
14,Bulgaria,2022,3.56,"168,354.30",15.325259,1.1,3322.0,49.314815,594.259259,253.0,73.787037,345.44,43874.27
15,Bulgaria,2023,4.90,"184,875.00",9.442841,1.1,5338.0,70.307692,649.230769,371.0,79.230769,NaN,45999.05
16,Bulgaria,2024,3.96,"204,906.90",2.446519,1.1,10290.0,NaN,NaN,NaN,NaN,NaN,NaN
17,Bulgaria,2025,4.93,NaN,4.580844,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
18,Croatia,2020,1.48,"50,744.00",0.154811,-1.4,1148.0,39.325301,403.164557,97.0,57.761446,286.20,38311.38
19,Croatia,2021,3.01,"58,343.10",2.554507,1.6,3514.0,40.904348,493.391304,168.0,64.046957,308.73,40745.01

In [40]:
# Save the full merged dataset
merged_df.to_csv(r"C:\Users\Disha\TU Braunschweig\Thesis\Data_2025\Merged Dataset.csv", index=False)