In [1]:
# Import libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import glob
import os

**Step 1: Merging all country files in the target folder: AF Market share of total registrations (M1)**

In [2]:
# Path to all country-level Excel files
target_files_marketShare = glob.glob(r"C:\Users\Disha\TU Braunschweig\Thesis\Data\Target\AF Market share of total registrations (M1)\*.csv")

# To make sure the files are present
print("Files found:", len(target_files_marketShare))
print(target_files_marketShare[:5])

Files found: 27
['C:\\Users\\Disha\\TU Braunschweig\\Thesis\\Data\\Target\\AF Market share of total registrations (M1)\\Austria.csv', 'C:\\Users\\Disha\\TU Braunschweig\\Thesis\\Data\\Target\\AF Market share of total registrations (M1)\\Belgium.csv', 'C:\\Users\\Disha\\TU Braunschweig\\Thesis\\Data\\Target\\AF Market share of total registrations (M1)\\Bulgaria.csv', 'C:\\Users\\Disha\\TU Braunschweig\\Thesis\\Data\\Target\\AF Market share of total registrations (M1)\\Croatia.csv', 'C:\\Users\\Disha\\TU Braunschweig\\Thesis\\Data\\Target\\AF Market share of total registrations (M1)\\Cyprus.csv']

In [3]:
target_list = []

for file in target_files_marketShare:
    
    # Extract country name from filename 
    country = os.path.basename(file).split(".")[0]
    
    # Read the CSV/Excel file
    df = pd.read_csv(file)
    # If Excel files, use: pd.read_excel(file)
    
    # Rename the first column to 'Year' (previously 'Category')
    df = df.rename(columns={df.columns[0]: "Year"})
    
    # Keep only required columns
    df = df[["Year", "BEV"]].copy()
    
    # Clean up 'Country' values (remove "(Target)" if it exists)
    df["Country"] = country.replace("(Target)", "").strip()
    
    # Ensure Year is numeric
    df = df[pd.to_numeric(df["Year"], errors="coerce").notnull()]
    df["Year"] = df["Year"].astype(int)
    
    # Rearranging the columns
    df = df[["Country", "Year", "BEV"]]
    
    # Append to the list
    target_list.append(df)

# Combine all countries into one DataFrame
targets_marketShare = pd.concat(target_list, ignore_index=True)

print("Target data combined. Shape:", targets_marketShare.shape)
display(targets_marketShare.head())

Target data combined. Shape: (486, 3)

   Country  Year   BEV
0  Austria  2008   NaN
1  Austria  2009  0.01
2  Austria  2010  0.03
3  Austria  2011  0.18
4  Austria  2012  0.13

In [4]:
targets_marketShare['Country'].unique()

array(['Austria', 'Belgium', 'Bulgaria', 'Croatia', 'Cyprus',
       'Czech Republic', 'Denmark', 'Estonia', 'Finland', 'France',
       'Germany', 'Greece', 'Hungary', 'Ireland', 'Italy', 'Latvia',
       'Lithuania', 'Luxembourg', 'Malta', 'Netherlands', 'Poland',
       'Portugal', 'Romania', 'Slovakia', 'Slovenia', 'Spain', 'Sweden'],
      dtype=object)

In [5]:
# Keep only those countries those are part of EU27
countries_to_remove = [
    'European Union (EU27)', 'Iceland', 'Liechtenstein', 'Norway',
    'Switzerland', 'Turkey', 'United Kingdom'
]

targets_marketShare = targets_marketShare[~targets_marketShare['Country'].isin(countries_to_remove)]

targets_marketShare['Country'].unique()

array(['Austria', 'Belgium', 'Bulgaria', 'Croatia', 'Cyprus',
       'Czech Republic', 'Denmark', 'Estonia', 'Finland', 'France',
       'Germany', 'Greece', 'Hungary', 'Ireland', 'Italy', 'Latvia',
       'Lithuania', 'Luxembourg', 'Malta', 'Netherlands', 'Poland',
       'Portugal', 'Romania', 'Slovakia', 'Slovenia', 'Spain', 'Sweden'],
      dtype=object)

**Step 2: Merging all country files in the target folder: AF New registrations (M1)**

In [6]:
# Path to all country-level Excel files
target_files_newReg = glob.glob(r"C:\Users\Disha\TU Braunschweig\Thesis\Data\Target\AF New registrations (M1)\*.csv")

# To make sure the files are present
print("Files found:", len(target_files_newReg))
print(target_files_newReg[:5])

Files found: 27
['C:\\Users\\Disha\\TU Braunschweig\\Thesis\\Data\\Target\\AF New registrations (M1)\\Austria.csv', 'C:\\Users\\Disha\\TU Braunschweig\\Thesis\\Data\\Target\\AF New registrations (M1)\\Belgium.csv', 'C:\\Users\\Disha\\TU Braunschweig\\Thesis\\Data\\Target\\AF New registrations (M1)\\Bulgaria.csv', 'C:\\Users\\Disha\\TU Braunschweig\\Thesis\\Data\\Target\\AF New registrations (M1)\\Croatia.csv', 'C:\\Users\\Disha\\TU Braunschweig\\Thesis\\Data\\Target\\AF New registrations (M1)\\Cyprus.csv']

In [7]:
target_list = []

for file in target_files_newReg:
    
    # Extract country name from filename 
    country = os.path.basename(file).split(".")[0]
    
    # Read the CSV/Excel file
    df = pd.read_csv(file)
    # If Excel files, use: pd.read_excel(file)
    
    # Rename the first column to 'Year' (previously 'Category')
    df = df.rename(columns={df.columns[0]: "Year"})
    
    # Keep only required columns
    df = df[["Year", "BEV"]].copy()
    
    # Clean up 'Country' values (remove "(Target)" if it exists)
    df["Country"] = country.replace("(Target)", "").strip()
    
    # Ensure Year is numeric
    df = df[pd.to_numeric(df["Year"], errors="coerce").notnull()]
    df["Year"] = df["Year"].astype(int)
    
    # Rearranging the columns
    df = df[["Country", "Year", "BEV"]]
    
    # Append to the list
    target_list.append(df)

# Combine all countries into one DataFrame
targets_newReg = pd.concat(target_list, ignore_index=True)

print("Target data combined. Shape:", targets_newReg.shape)
display(targets_newReg.head())

Target data combined. Shape: (486, 3)

   Country  Year    BEV
0  Austria  2008    0.0
1  Austria  2009   25.0
2  Austria  2010  112.0
3  Austria  2011  631.0
4  Austria  2012  427.0

In [8]:
targets_newReg['Country'].nunique()

27

**Step 3: Gross Domestic Product (GDP)**

In [9]:
# Read the GDP data
gdp_wide = pd.read_csv(r"C:\Users\Disha\TU Braunschweig\Thesis\Data\Parameters\GDP_EU27_Anually.csv")
gdp_wide.head()

,Country,2011,2012,2013,2014,2015,2016,2017,2018,2019,2020,2021,2022,2023,2024
0,Austria,"308,167.0","316,589.4","321,191.7","330,113.5","342,083.5","355,665.6","367,294.9","383,234.3","395,706.8","380,317.9","406,231.5","449,382.2","477,837.3","494,087.6"
1,Belgium,"378,745.4","387,934.9","394,616.3","404,958.3","415,538.0","428,467.1","443,407.2","459,491.8","479,444.9","463,750.9","506,047.2","561,309.1","602,376.3","620,271.8"
2,Bulgaria,"81,126.3","82,642.8","82,253.4","84,147.7","89,571.4","95,349.4","102,683.0","109,525.9","119,685.9","120,979.0","139,536.6","168,354.3","184,875.0","204,906.9"
3,Croatia,"45,178.9","44,791.5","45,061.5","44,867.9","45,965.7","47,565.9","49,732.5","52,216.7","54,905.5","50,744.0","58,343.1","67,613.0","79,186.3","85,905.2"
4,Cyprus,"19,858.1","19,495.4","18,040.3","17,482.8","17,944.2","19,013.8","20,312.4","21,807.8","23,400.9","22,373.6","25,679.9","29,645.4","32,439.2","34,770.2"

In [10]:
# Transpose the datset 
gdp = gdp_wide.melt(id_vars="Country", var_name="Year", value_name="GDP")

# Sort by Country and then Year
gdp = gdp.sort_values(by=["Country", "Year"]).reset_index(drop=True)

# Display
gdp.head()

   Country  Year        GDP
0  Austria  2011  308,167.0
1  Austria  2012  316,589.4
2  Austria  2013  321,191.7
3  Austria  2014  330,113.5
4  Austria  2015  342,083.5

In [11]:
gdp['Country'].unique()

array(['Austria', 'Belgium', 'Bulgaria', 'Croatia', 'Cyprus', 'Czechia',
       'Denmark', 'Estonia', 'Finland', 'France', 'Germany', 'Greece',
       'Hungary', 'Ireland', 'Italy', 'Latvia', 'Lithuania', 'Luxembourg',
       'Malta', 'Netherlands', 'Poland', 'Portugal', 'Romania',
       'Slovakia', 'Slovenia', 'Spain', 'Sweden'], dtype=object)

In [12]:
# Rename the name from 'Czechia' to 'Czech Republic'
gdp.loc[gdp['Country'] == 'Czechia', 'Country'] = 'Czech Republic'
gdp['Country'].unique()

array(['Austria', 'Belgium', 'Bulgaria', 'Croatia', 'Cyprus',
       'Czech Republic', 'Denmark', 'Estonia', 'Finland', 'France',
       'Germany', 'Greece', 'Hungary', 'Ireland', 'Italy', 'Latvia',
       'Lithuania', 'Luxembourg', 'Malta', 'Netherlands', 'Poland',
       'Portugal', 'Romania', 'Slovakia', 'Slovenia', 'Spain', 'Sweden'],
      dtype=object)

**Step 4: Consumer Price Index (CPI)**

In [13]:
# Read the CPI data
cpi_wide = pd.read_csv(r"C:\Users\Disha\TU Braunschweig\Thesis\Data\Parameters\ConsumerPriceIndex_EU27_Anually.csv")
cpi_wide.head()

,DATASET,SERIES_CODE,OBS_MEASURE,COUNTRY,INDEX_TYPE,COICOP_1999,TYPE_OF_TRANSFORMATION,FREQUENCY,SCALE,2011,...,2015,2016,2017,2018,2019,2020,2021,2022,2023,2024
0,IMF.STA:CPI(5.0.0),AUT.CPI._T.YOY_PCH_PA_PT.A,OBS_VALUE,Austria,Consumer price index (CPI),All Items,"Period average, Year-over-year (YOY) percent c...",Annual,Units,3.286579,...,0.896563,0.891592,2.081269,1.998380,1.530896,1.381911,2.766667,8.546870,7.814134,2.937916
1,IMF.STA:CPI(5.0.0),BEL.CPI._T.YOY_PCH_PA_PT.A,OBS_VALUE,Belgium,Consumer price index (CPI),All Items,"Period average, Year-over-year (YOY) percent c...",Annual,Units,3.532082,...,0.561429,1.973853,2.125971,2.053165,1.436820,0.740792,2.440249,9.597512,4.049011,3.143491
2,IMF.STA:CPI(5.0.0),DNK.CPI._T.YOY_PCH_PA_PT.A,OBS_VALUE,Denmark,Consumer price index (CPI),All Items,"Period average, Year-over-year (YOY) percent c...",Annual,Units,2.758682,...,0.452034,0.250000,1.147132,0.813609,0.758132,0.420712,1.853045,7.696567,3.305178,1.372200
3,IMF.STA:CPI(5.0.0),FRA.CPI._T.YOY_PCH_PA_PT.A,OBS_VALUE,France,Consumer price index (CPI),All Items,"Period average, Year-over-year (YOY) percent c...",Annual,Units,2.111598,...,0.037514,0.183335,1.032283,1.850815,1.108255,0.476499,1.642331,5.222367,4.878357,1.999049
4,IMF.STA:CPI(5.0.0),DEU.CPI._T.YOY_PCH_PA_PT.A,OBS_VALUE,Germany,Consumer price index (CPI),All Items,"Period average, Year-over-year (YOY) percent c...",Annual,Units,2.075173,...,0.514426,0.491747,1.509495,1.732169,1.445660,0.144878,3.066667,6.872574,5.946437,2.256498

In [14]:
# Drop unwanted columns
cpi_wide = cpi_wide.drop(columns=['DATASET','SERIES_CODE', 'OBS_MEASURE', 'INDEX_TYPE', 'COICOP_1999',
                        'TYPE_OF_TRANSFORMATION', 'FREQUENCY', 'SCALE'])
cpi_wide.head()

,COUNTRY,2011,2012,2013,2014,2015,2016,2017,2018,2019,2020,2021,2022,2023,2024
0,Austria,3.286579,2.485676,2.000156,1.605812,0.896563,0.891592,2.081269,1.998380,1.530896,1.381911,2.766667,8.546870,7.814134,2.937916
1,Belgium,3.532082,2.839663,1.113096,0.340003,0.561429,1.973853,2.125971,2.053165,1.436820,0.740792,2.440249,9.597512,4.049011,3.143491
2,Denmark,2.758682,2.397915,0.789072,0.564021,0.452034,0.250000,1.147132,0.813609,0.758132,0.420712,1.853045,7.696567,3.305178,1.372200
3,France,2.111598,1.954195,0.863715,0.507759,0.037514,0.183335,1.032283,1.850815,1.108255,0.476499,1.642331,5.222367,4.878357,1.999049
4,Germany,2.075173,2.008489,1.504723,0.906794,0.514426,0.491747,1.509495,1.732169,1.445660,0.144878,3.066667,6.872574,5.946437,2.256498

In [15]:
# Sort by Country alphabetically
cpi_wide = cpi_wide.sort_values(by="COUNTRY").reset_index(drop=True)

# Display result
cpi_wide.head()

,COUNTRY,2011,2012,2013,2014,2015,2016,2017,2018,2019,2020,2021,2022,2023,2024
0,Austria,3.286579,2.485676,2.000156,1.605812,0.896563,0.891592,2.081269,1.998380,1.530896,1.381911,2.766667,8.546870,7.814134,2.937916
1,Belgium,3.532082,2.839663,1.113096,0.340003,0.561429,1.973853,2.125971,2.053165,1.436820,0.740792,2.440249,9.597512,4.049011,3.143491
2,Bulgaria,4.219903,2.954568,0.890094,-1.418184,-0.104633,-0.798650,2.061596,2.814545,3.103729,1.672441,3.297744,15.325259,9.442841,2.446519
3,"Croatia, Republic of",2.272727,3.412073,2.216582,-0.215196,-0.464499,-1.125000,1.129372,1.500125,0.771820,0.154811,2.554507,10.780581,7.941282,2.972005
4,Cyprus,3.289449,2.389054,-0.399358,-1.354989,-2.096998,-1.429167,0.531766,1.435491,0.250371,-0.638423,2.446089,8.395483,3.541342,1.800230

In [16]:
# Rename column
cpi_wide = cpi_wide.rename(columns={"COUNTRY": "Country"})

# Remove "Republic of " prefix from country names
cpi_wide["Country"] = cpi_wide["Country"].str.split(",").str[0].str.strip()

# Display
cpi_wide.head()

,Country,2011,2012,2013,2014,2015,2016,2017,2018,2019,2020,2021,2022,2023,2024
0,Austria,3.286579,2.485676,2.000156,1.605812,0.896563,0.891592,2.081269,1.998380,1.530896,1.381911,2.766667,8.546870,7.814134,2.937916
1,Belgium,3.532082,2.839663,1.113096,0.340003,0.561429,1.973853,2.125971,2.053165,1.436820,0.740792,2.440249,9.597512,4.049011,3.143491
2,Bulgaria,4.219903,2.954568,0.890094,-1.418184,-0.104633,-0.798650,2.061596,2.814545,3.103729,1.672441,3.297744,15.325259,9.442841,2.446519
3,Croatia,2.272727,3.412073,2.216582,-0.215196,-0.464499,-1.125000,1.129372,1.500125,0.771820,0.154811,2.554507,10.780581,7.941282,2.972005
4,Cyprus,3.289449,2.389054,-0.399358,-1.354989,-2.096998,-1.429167,0.531766,1.435491,0.250371,-0.638423,2.446089,8.395483,3.541342,1.800230

In [17]:
# Transpose the datset 
cpi = cpi_wide.melt(id_vars="Country", var_name="Year", value_name="CPI")

# Sort by Country and then Year
cpi = cpi.sort_values(by=["Country", "Year"]).reset_index(drop=True)

# Display
cpi.head()

   Country  Year       CPI
0  Austria  2011  3.286579
1  Austria  2012  2.485676
2  Austria  2013  2.000156
3  Austria  2014  1.605812
4  Austria  2015  0.896563

In [18]:
cpi['Country'].unique()

array(['Austria', 'Belgium', 'Bulgaria', 'Croatia', 'Cyprus',
       'Czech Republic', 'Denmark', 'Estonia', 'Finland', 'France',
       'Germany', 'Greece', 'Hungary', 'Ireland', 'Italy', 'Latvia',
       'Lithuania', 'Luxembourg', 'Malta', 'Netherlands', 'Poland',
       'Portugal', 'Romania', 'Slovak Republic', 'Slovenia', 'Spain',
       'Sweden'], dtype=object)

In [19]:
# Rename the name from 'Czechia' to 'Czech Republic'
cpi.loc[cpi['Country'] == 'Slovak Republic', 'Country'] = 'Slovakia'
cpi['Country'].unique()

array(['Austria', 'Belgium', 'Bulgaria', 'Croatia', 'Cyprus',
       'Czech Republic', 'Denmark', 'Estonia', 'Finland', 'France',
       'Germany', 'Greece', 'Hungary', 'Ireland', 'Italy', 'Latvia',
       'Lithuania', 'Luxembourg', 'Malta', 'Netherlands', 'Poland',
       'Portugal', 'Romania', 'Slovakia', 'Slovenia', 'Spain', 'Sweden'],
      dtype=object)

**Step 5: Employment Growth**

In [20]:
# Read the Employment Growth data
eg_wide = pd.read_csv(r"C:\Users\Disha\TU Braunschweig\Thesis\Data\Parameters\EmploymentGrowth_EU27_Anually.csv")
eg_wide.head()

,Country,2005,2006,2007,2008,2009,2010,2011,2012,2013,...,2015,2016,2017,2018,2019,2020,2021,2022,2023,2024
0,Belgium,1.4,1.1,1.7,1.8,-0.1,0.7,1.2,0.2,-0.2,...,0.8,1.3,1.5,1.5,1.6,-0.1,1.7,1.9,0.8,0.3
1,Bulgaria,2.7,3.3,3.2,2.4,-1.7,-3.9,-2.2,-2.5,-0.4,...,0.4,0.5,1.8,-0.1,-1.5,-1.8,0.1,1.1,1.1,1.1
2,Czechia,1.9,1.3,2.1,2.2,-1.8,-1.0,-0.5,0.5,0.4,...,1.4,1.0,1.3,1.2,-0.1,-2.3,1.0,1.0,1.6,0.6
3,Denmark,1.4,2.3,2.3,1.3,-3.1,-2.3,-0.1,-0.7,0.0,...,1.5,1.6,1.5,1.5,1.4,-1.1,2.3,4.0,1.1,0.7
4,Germany,-0.1,0.7,1.7,1.4,0.1,0.5,1.1,1.2,0.7,...,0.9,1.3,1.4,1.3,0.9,-0.7,0.2,1.3,0.7,0.1

In [21]:
# Transpose the datset 
eg = eg_wide.melt(id_vars="Country", var_name="Year", value_name="EG")

# Sort by Country and then Year
eg = eg.sort_values(by=["Country", "Year"]).reset_index(drop=True)

# Display
eg.head()

   Country  Year EG
0  Albania  2005  :
1  Albania  2006  :
2  Albania  2007  :
3  Albania  2008  :
4  Albania  2009  :

In [22]:
eg['Country'].unique()

array(['Albania', 'Austria', 'Belgium', 'Bulgaria', 'Croatia', 'Cyprus',
       'Czechia', 'Denmark', 'Estonia', 'Finland', 'France', 'Germany',
       'Greece', 'Hungary', 'Iceland', 'Ireland', 'Italy', 'Kosovo*',
       'Latvia', 'Liechtenstein', 'Lithuania', 'Luxembourg', 'Malta',
       'Montenegro', 'Netherlands', 'North Macedonia', 'Norway', 'Poland',
       'Portugal', 'Romania', 'Serbia', 'Slovakia', 'Slovenia', 'Spain',
       'Sweden', 'Switzerland', 'Türkiye', 'United Kingdom'], dtype=object)

In [23]:
# Keep only those countries those are part of EU27
countries_to_remove = [
    'Albania', 'Iceland', 'Norway', 'Kosovo*', 'Liechtenstein',
    'Montenegro', 'North Macedonia','Switzerland', 'Türkiye', 'United Kingdom', 'Serbia'
]

eg = eg[~eg['Country'].isin(countries_to_remove)]

eg['Country'].unique()

array(['Austria', 'Belgium', 'Bulgaria', 'Croatia', 'Cyprus', 'Czechia',
       'Denmark', 'Estonia', 'Finland', 'France', 'Germany', 'Greece',
       'Hungary', 'Ireland', 'Italy', 'Latvia', 'Lithuania', 'Luxembourg',
       'Malta', 'Netherlands', 'Poland', 'Portugal', 'Romania',
       'Slovakia', 'Slovenia', 'Spain', 'Sweden'], dtype=object)

In [24]:
# Rename the name from 'Czechia' to 'Czech Republic'
eg.loc[eg['Country'] == 'Czechia', 'Country'] = 'Czech Republic'
eg['Country'].unique()

array(['Austria', 'Belgium', 'Bulgaria', 'Croatia', 'Cyprus',
       'Czech Republic', 'Denmark', 'Estonia', 'Finland', 'France',
       'Germany', 'Greece', 'Hungary', 'Ireland', 'Italy', 'Latvia',
       'Lithuania', 'Luxembourg', 'Malta', 'Netherlands', 'Poland',
       'Portugal', 'Romania', 'Slovakia', 'Slovenia', 'Spain', 'Sweden'],
      dtype=object)

**Step 6: Recharging Points**

In [25]:
# Path to all country-level Excel files
recharge_files_2019 = glob.glob(r"C:\Users\Disha\TU Braunschweig\Thesis\Data\Parameters\Recharging points (2012-2019)\*.csv")

# To make sure the files are present
print("Files found:", len(recharge_files_2019))
print(recharge_files_2019[:5])

Files found: 33
['C:\\Users\\Disha\\TU Braunschweig\\Thesis\\Data\\Parameters\\Recharging points (2012-2019)\\Austria.csv', 'C:\\Users\\Disha\\TU Braunschweig\\Thesis\\Data\\Parameters\\Recharging points (2012-2019)\\Belgium.csv', 'C:\\Users\\Disha\\TU Braunschweig\\Thesis\\Data\\Parameters\\Recharging points (2012-2019)\\Bulgaria.csv', 'C:\\Users\\Disha\\TU Braunschweig\\Thesis\\Data\\Parameters\\Recharging points (2012-2019)\\Croatia.csv', 'C:\\Users\\Disha\\TU Braunschweig\\Thesis\\Data\\Parameters\\Recharging points (2012-2019)\\Cyprus.csv']

In [26]:
recharging_2019_list = []

for file in recharge_files_2019:
    
    # Extract country name from filename 
    country = os.path.basename(file).split(".")[0]
    
    # Read the CSV file
    df_2019 = pd.read_csv(file)
    
    # Rename the first column to 'Year'
    df_2019 = df_2019.rename(columns={df_2019.columns[0]: "Year"})
    
    # Rename the second column (which is the country name) to 'Recharging Points'
    df_2019 = df_2019.rename(columns={df_2019.columns[1]: "Recharging Points"})
    
    # Clean up Year column and keep only valid numeric years
    df_2019 = df_2019[pd.to_numeric(df_2019["Year"], errors="coerce").notnull()]
    df_2019["Year"] = df_2019["Year"].astype(int)
    
    # Add a Country column
    df_2019["Country"] = country.replace("(Target)", "").strip()
    
    # Reorder columns
    df_2019 = df_2019[["Country", "Year", "Recharging Points"]]
    
    # Append to list
    recharging_2019_list.append(df_2019)

# Combine all countries into one DataFrame
recharge_files_2019 = pd.concat(recharging_2019_list, ignore_index=True)

print("Target data combined. Shape:", recharge_files_2019.shape)
display(recharge_files_2019.head())

Target data combined. Shape: (264, 3)

   Country  Year  Recharging Points
0  Austria  2012             1063.0
1  Austria  2013             1173.0
2  Austria  2014             1393.0
3  Austria  2015             1625.0
4  Austria  2016             1998.0

In [27]:
# Path to all country-level Excel files
recharge_files_2025 = glob.glob(r"C:\Users\Disha\TU Braunschweig\Thesis\Data\Parameters\Recharging points (2020-2025)\*.csv")

# To make sure the files are present
print("Files found:", len(recharge_files_2025))
print(recharge_files_2025[:5])

Files found: 33
['C:\\Users\\Disha\\TU Braunschweig\\Thesis\\Data\\Parameters\\Recharging points (2020-2025)\\Austria.csv', 'C:\\Users\\Disha\\TU Braunschweig\\Thesis\\Data\\Parameters\\Recharging points (2020-2025)\\Belgium.csv', 'C:\\Users\\Disha\\TU Braunschweig\\Thesis\\Data\\Parameters\\Recharging points (2020-2025)\\Bulgaria.csv', 'C:\\Users\\Disha\\TU Braunschweig\\Thesis\\Data\\Parameters\\Recharging points (2020-2025)\\Croatia.csv', 'C:\\Users\\Disha\\TU Braunschweig\\Thesis\\Data\\Parameters\\Recharging points (2020-2025)\\Cyprus.csv']

In [28]:
recharging_2025_list = []

for file in recharge_files_2025:
    
    # Extract country name from filename 
    country = os.path.basename(file).split(".")[0]
    
    # Read the CSV file
    df_2025 = pd.read_csv(file)
    
    # Rename first column to 'Period'
    df_2025 = df_2025.rename(columns={df_2025.columns[0]: "Period"})
    
    # Extract numeric year from 'Period' (e.g. '2020 Q1' -> 2020)
    df_2025["Year"] = df_2025["Period"].str.extract(r"(\d{4})").astype(int)
    
    # Group by year to sum all quarters (sum AC and DC, individually)
    df_2025_yearly = df_2025.groupby("Year", as_index=False)[["AC", "DC"]].sum()
    
    # Add total recharging points (AC + DC)
    df_2025_yearly["Recharging Points"] = df_2025_yearly["AC"] + df_2025_yearly["DC"]
    
    # Add country name
    df_2025_yearly["Country"] = country.replace("(Target)", "").strip()
    
    # Reorder columns
    df_2025_yearly = df_2025_yearly[["Country", "Year", "Recharging Points"]]
    
    # Append to list
    recharging_2025_list.append(df_2025_yearly)

# Combine all countries into one DataFrame
recharge_files_2025 = pd.concat(recharging_2025_list, ignore_index=True)

print("Target data combined. Shape:", recharge_files_2025.shape)
display(recharge_files_2025.head())

Target data combined. Shape: (198, 3)

   Country  Year  Recharging Points
0  Austria  2020            26797.0
1  Austria  2021            39904.0
2  Austria  2022            61393.0
3  Austria  2023            76773.0
4  Austria  2024           102562.0

In [29]:
# Combine both dataframe (recharge_files_2019 and recharge_files_2025)

# Make sure both dataframes exist
print("Old data:", recharge_files_2019.shape)
print("New data:", recharge_files_2025.shape)

# Ensure same column names and order
recharge_files_2019 = recharge_files_2019[["Country", "Year", "Recharging Points"]]
recharge_files_2025 = recharge_files_2025[["Country", "Year", "Recharging Points"]]

# Concatenate vertically
recharging_points = pd.concat(
    [recharge_files_2019, recharge_files_2025], 
    ignore_index=True
)

# Keep only rows where Year <= 2024 
recharging_points = recharging_points[recharging_points["Year"] <= 2024]

# Sort by Country and Year
recharging_points = recharging_points.sort_values(
    by=["Country", "Year"]
).reset_index(drop=True)

# Check the result
print("Combined dataset shape:", recharging_points.shape)
display(recharging_points.head(15))

Old data: (264, 3)
New data: (198, 3)
Combined dataset shape: (429, 3)

    Country  Year  Recharging Points
0   Austria  2012             1063.0
1   Austria  2013             1173.0
2   Austria  2014             1393.0
3   Austria  2015             1625.0
4   Austria  2016             1998.0
5   Austria  2017             3842.0
6   Austria  2018             4079.0
7   Austria  2019             7694.0
8   Austria  2020            26797.0
9   Austria  2021            39904.0
10  Austria  2022            61393.0
11  Austria  2023            76773.0
12  Austria  2024           102562.0
13  Belgium  2012                NaN
14  Belgium  2013              378.0

In [30]:
recharging_points['Country'].unique()

array(['Austria', 'Belgium', 'Bulgaria', 'Croatia', 'Cyprus',
       'Czech Republic', 'Denmark', 'Estonia', 'Finland', 'France',
       'Germany', 'Greece', 'Hungary', 'Iceland', 'Ireland', 'Italy',
       'Latvia', 'Liechtenstein', 'Lithuania', 'Luxembourg', 'Malta',
       'Netherlands', 'Norway', 'Poland', 'Portugal', 'Romania',
       'Slovakia', 'Slovenia', 'Spain', 'Sweden', 'Switzerland', 'Turkey',
       'United Kingdom'], dtype=object)

In [31]:
# Keep only those countries those are part of EU27
countries_to_remove = [
    'Iceland', 'Norway', 'Liechtenstein',
    'Switzerland', 'Turkey', 'United Kingdom'
]

recharging_points = recharging_points[~recharging_points['Country'].isin(countries_to_remove)]

recharging_points['Country'].unique()

array(['Austria', 'Belgium', 'Bulgaria', 'Croatia', 'Cyprus',
       'Czech Republic', 'Denmark', 'Estonia', 'Finland', 'France',
       'Germany', 'Greece', 'Hungary', 'Ireland', 'Italy', 'Latvia',
       'Lithuania', 'Luxembourg', 'Malta', 'Netherlands', 'Poland',
       'Portugal', 'Romania', 'Slovakia', 'Slovenia', 'Spain', 'Sweden'],
      dtype=object)

**Step 7: Merge these datasets with the target**

In [32]:
# Ensure 'Year' is numeric in all datasets
targets_marketShare["Year"] = targets_marketShare["Year"].astype(int)
targets_newReg["Year"] = targets_newReg["Year"].astype(int)
gdp["Year"] = gdp["Year"].astype(int)
cpi["Year"] = cpi["Year"].astype(int)
eg["Year"] = eg["Year"].astype(int)
recharging_points["Year"] = recharging_points["Year"].astype(int)

# Ensure 'Country' is string in all datasets
targets_marketShare["Country"] = targets_marketShare["Country"].astype(str)
targets_newReg["Country"] = targets_newReg["Country"].astype(str)
gdp["Country"] = gdp["Country"].astype(str)
cpi["Country"] = cpi["Country"].astype(str)
eg["Country"] = eg["Country"].astype(str)
recharging_points["Country"] = recharging_points["Country"].astype(str)

In [33]:
# Filter target dataset to years 2011-2024
targets_filtered_marketShare = targets_marketShare[(targets_marketShare["Year"] >= 2011) & (targets_marketShare["Year"] <= 2024)]

# Merge with AF New registrations (M1)
merged_w_newReg = pd.merge(targets_filtered_marketShare, targets_newReg, on=["Country", "Year"], how="left")

# Merge with GDP
merged_w_gdp = pd.merge(merged_w_newReg, gdp, on=["Country", "Year"], how="left")

# Merge with CPI
merged_w_cpi = pd.merge(merged_w_gdp, cpi, on=["Country", "Year"], how="left")

# Merge with Employment Growth
merged_eg = pd.merge(merged_w_cpi, eg, on=["Country", "Year"], how="left")

# Merge with Recharging Points
merged_df = pd.merge(merged_eg, recharging_points, on=["Country", "Year"], how="left")

# Result
print("Shape of merged dataset:", merged_df.shape)
merged_df.head()

Shape of merged dataset: (378, 8)

   Country  Year  BEV_x   BEV_y        GDP       CPI   EG  Recharging Points
0  Austria  2011   0.18   631.0  308,167.0  3.286579  1.6                NaN
1  Austria  2012   0.13   427.0  316,589.4  2.485676  1.0             1063.0
2  Austria  2013   0.21   656.0  321,191.7  2.000156  0.4             1173.0
3  Austria  2014   0.44  1344.0  330,113.5  1.605812  1.0             1393.0
4  Austria  2015   0.55  1699.0  342,083.5  0.896563  0.6             1625.0

In [34]:
# Rename BEV columns
merged_df.rename(columns={
    'BEV_x': 'BEV Percentage (Total Number Of Registrations)',
    'BEV_y': 'BEV (New Registrations)'
}, inplace=True)

merged_df.head()

,Country,Year,BEV Percentage (Total Number Of Registrations),BEV (New Registrations),GDP,CPI,EG,Recharging Points
0,Austria,2011,0.18,631.0,"308,167.0",3.286579,1.6,NaN
1,Austria,2012,0.13,427.0,"316,589.4",2.485676,1.0,1063.0
2,Austria,2013,0.21,656.0,"321,191.7",2.000156,0.4,1173.0
3,Austria,2014,0.44,1344.0,"330,113.5",1.605812,1.0,1393.0
4,Austria,2015,0.55,1699.0,"342,083.5",0.896563,0.6,1625.0

**Step 8: Merge the EU average dataset with the country-wise merged dataset**

In [35]:
# Import the datasets
RechargeSpeed = pd.read_csv(r"C:\Users\Disha\TU Braunschweig\Thesis\Data\Parameters\AC and DC Average Recharging Speed of Available BEV Models.csv")
AvailableBEV = pd.read_csv(r"C:\Users\Disha\TU Braunschweig\Thesis\Data\Parameters\Available Battery Electric Vehicle models in Europ per year.csv")
AverageBatteryCapacity = pd.read_csv(r"C:\Users\Disha\TU Braunschweig\Thesis\Data\Parameters\Average Battery Capacity of Available BEV models per year.csv")
AverageRange = pd.read_csv(r"C:\Users\Disha\TU Braunschweig\Thesis\Data\Parameters\Average Range of BEV models per year.csv")
AverageRetailPrice = pd.read_csv(r"C:\Users\Disha\TU Braunschweig\Thesis\Data\Parameters\Average Retail Price of BEV models per year.csv")

In [36]:
RechargeSpeed.head()

   Category  AC Recharging Speed (km/h)  DC Recharging Speed (km/h)
0      2011                       17.50                      175.00
1      2013                       48.20                      270.00
2      2014                       22.60                      240.00
3      2015                       47.70                      381.25
4      2016                       44.85                      371.50

In [37]:
AvailableBEV.head()

   Category  Available
0      2011          4
1      2012          4
2      2013          8
3      2014         13
4      2015         21

In [38]:
AverageBatteryCapacity.head()

   Category  Battery Capacity
0      2011            16.375
1      2013            32.900
2      2014            33.260
3      2015            56.410
4      2016            62.485

In [39]:
AverageRange.head()

   Category  Real Range
0      2011       95.00
1      2012       95.00
2      2013      142.22
3      2014      155.77
4      2015      215.22

In [40]:
AverageRetailPrice.head()

   Category  Purchase price (EUR)
0      2013              30469.93
1      2014              35555.64
2      2015              42052.00
3      2016              39789.11
4      2017              44717.86

In [41]:
# Ensure all datasets have column named 'Year' as int
for df in [RechargeSpeed, AvailableBEV, AverageBatteryCapacity, AverageRange, AverageRetailPrice]:
    
    # Rename year column if needed
    if "Category" in df.columns:
        df.rename(columns={"Category": "Year"}, inplace=True)
    df["Year"] = df["Year"].astype(int)

In [42]:
# Merge with your country-level merged_df on 'Year' only
merged_df = merged_df.merge(RechargeSpeed, on="Year", how="left") \
                     .merge(AvailableBEV, on="Year", how="left") \
                     .merge(AverageBatteryCapacity, on="Year", how="left") \
                     .merge(AverageRange, on="Year", how="left") \
                     .merge(AverageRetailPrice, on="Year", how="left")

In [43]:
# Check result
print("Shape of final merged dataset:", merged_df.shape)
merged_df.head(20)

Shape of final merged dataset: (378, 14)

,Country,Year,BEV Percentage (Total Number Of Registrations),BEV (New Registrations),GDP,CPI,EG,Recharging Points,AC Recharging Speed (km/h),DC Recharging Speed (km/h),Available,Battery Capacity,Real Range,Purchase price (EUR)
0,Austria,2011,0.18,631.0,"308,167.0",3.286579,1.6,NaN,17.500000,175.000000,4.0,16.375000,95.00,NaN
1,Austria,2012,0.13,427.0,"316,589.4",2.485676,1.0,1063.0,NaN,NaN,4.0,NaN,95.00,NaN
2,Austria,2013,0.21,656.0,"321,191.7",2.000156,0.4,1173.0,48.200000,270.000000,8.0,32.900000,142.22,30469.93
3,Austria,2014,0.44,1344.0,"330,113.5",1.605812,1.0,1393.0,22.600000,240.000000,13.0,33.260000,155.77,35555.64
4,Austria,2015,0.55,1699.0,"342,083.5",0.896563,0.6,1625.0,47.700000,381.250000,21.0,56.410000,215.22,42052.00
5,Austria,2016,1.15,3806.0,"355,665.6",0.891592,1.3,1998.0,44.850000,371.500000,23.0,62.485000,269.27,39789.11
6,Austria,2017,1.53,5398.0,"367,294.9",2.081269,1.7,3842.0,47.705882,267.272727,28.0,40.400000,221.75,44717.86
7,Austria,2018,1.99,6774.0,"383,234.3",1.998380,1.8,4079.0,48.714286,267.777778,29.0,41.200000,216.55,46225.88
8,Austria,2019,2.81,9242.0,"395,706.8",1.530896,1.1,7694.0,57.066667,458.928571,34.0,69.480000,300.68,42237.97
9,Austria,2020,6.41,15955.0,"380,317.9",1.381911,-1.6,26797.0,39.325301,403.164557,97.0,57.761446,286.20,38311.38
10,Austria,2021,13.92,33379.0,"406,231.5",2.766667,2.0,39904.0,40.904348,493.391304,168.0,64.046957,308.73,40745.01
11,Austria,2022,15.70,33768.0,"449,382.2",8.546870,2.7,61393.0,49.314815,594.259259,253.0,73.787037,345.44,43874.27
12,Austria,2023,19.91,47614.0,"477,837.3",7.814134,0.8,76773.0,70.307692,649.230769,371.0,79.230769,NaN,45999.05
13,Austria,2024,17.58,44622.0,"494,087.6",2.937916,0.1,102562.0,NaN,NaN,NaN,NaN,NaN,NaN
14,Belgium,2011,0.05,288.0,"378,745.4",3.532082,1.2,NaN,17.500000,175.000000,4.0,16.375000,95.00,NaN
15,Belgium,2012,0.12,585.0,"387,934.9",2.839663,0.2,NaN,NaN,NaN,4.0,NaN,95.00,NaN
16,Belgium,2013,0.10,494.0,"394,616.3",1.113096,-0.2,378.0,48.200000,270.000000,8.0,32.900000,142.22,30469.93
17,Belgium,2014,0.27,1339.0,"404,958.3",0.340003,0.4,614.0,22.600000,240.000000,13.0,33.260000,155.77,35555.64
18,Belgium,2015,0.32,1613.0,"415,538.0",0.561429,0.8,1437.0,47.700000,381.250000,21.0,56.410000,215.22,42052.00
19,Belgium,2016,0.41,2216.0,"428,467.1",1.973853,1.3,1620.0,44.850000,371.500000,23.0,62.485000,269.27,39789.11

In [44]:
# Save the full merged dataset
merged_df.to_csv(r"C:\Users\Disha\TU Braunschweig\Thesis\Data\Merged Dataset.csv", index=False)